name: unstable

on: 
  push:
    branches:
      - 'stable'
    tags: 
      - '*'

jobs:
    devel:
      runs-on: ubuntu-latest
      container:
        image: apnpucky/ubuntu-pip:20220726175949
      steps:
        - uses: APN-Pucky/make-python-action@main
          with:
            test: true
            doc: false
            pypi-token: ${{ secrets.pypi_token }}

